### ISSUE TITLE
list index out of range in phydms_prepalignments

### ISSUE THREAD

**Issue by mbdoud** [jbloomlab/phydms#4]
Beginning execution of phydms_prepalignment in directory /fh/fast/bloom_j/grp/mike/HAhomologs at time Fri Jul 22 15:24:57 2016

Version information:
	Time and date: Fri Jul 22 15:24:57 2016
	Platform: Linux-3.13.0-68-generic-x86_64-with-Ubuntu-14.04-trusty
	Python version: 2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]
	phydms version: 1.2.dev4
	Bio version: 1.67
	cython version: 0.23.4
	dms_tools version: 1.1.16
	scipy version: 0.17.0
	matplotlib version: 1.5.1

Parsed the following command-line arguments:
	inseqs = H3_WSNref.fa
	minidentity = 0.7
	prealigned = False
	purgeseqs = None
	minuniqueness = 2
	keepseqs = None
	refseq = Reference_WSN_HA_coding_sequence_mature_nostop
	alignment = H3_WSNalignment
	mafft = mafft

Read 8126 sequences from H3_WSNref.fa
Retained 8126 after removing those specified for purging by '--purgeseqs.'
Retained 8126 sequences after removing any with length not multiple of 3.
Retained 7445 sequences after purging any with ambiguous nucleotides.
Traceback (most recent call last):
  File "/home/mdoud/.local/bin//phydms_prepalignment", line 5, in <module>
    pkg_resources.run_script('phydms==1.2.dev4', 'phydms_prepalignment')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/home/mdoud/.local/lib/python2.7/site-packages/phydms-1.2.dev4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phydms_prepalignment", line 344, in <module>
    
  File "/home/mdoud/.local/lib/python2.7/site-packages/phydms-1.2.dev4-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phydms_prepalignment", line 189, in main
    
IndexError: list index out of range

**Comment by jbloom** [comment]
Should be fixed in new version on `GitHub`. The problem was that list elements were being popped as the list was being iterated on.
