### ISSUE TITLE
Error when using Pip to install phydms

### ISSUE THREAD

**Issue by kevinmyers** [jbloomlab/phydms#44]
I am using pip to install phydms - `pip install phydms`. When I do I get the following error:

```
Building wheels for collected packages: phydms
  Building wheel for phydms (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/setup.py", line 70, in <module>
          setup(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          _install_setup_requires(attrs)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 76, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 81, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/dist.py", line 640, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 798, in resolve
          dist = self._resolve_dist(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 834, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1104, in best_match
          return self.obtain(req, installer)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1115, in obtain
          return installer(requirement) if installer else None
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/.eggs/Cython-3.0.10-py3.10-macosx-10.9-x86_64.egg/Cython-3.0.10.dist-info' -> '/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/.eggs/Cython-3.0.10-py3.10-macosx-10.9-x86_64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for phydms
  Running setup.py clean for phydms
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/setup.py", line 70, in <module>
          setup(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          _install_setup_requires(attrs)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 76, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/__init__.py", line 81, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/dist.py", line 640, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 798, in resolve
          dist = self._resolve_dist(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 834, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1104, in best_match
          return self.obtain(req, installer)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1115, in obtain
          return installer(requirement) if installer else None
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/kevinmyers/opt/anaconda3/envs/dms_tools2/lib/python3.10/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/.eggs/Cython-3.0.10-py3.10-macosx-10.9-x86_64.egg/Cython-3.0.10.dist-info' -> '/private/var/folders/sl/jyxzdp856v70v9s_8s8mczbm0000gq/T/pip-install-f01x632f/phydms_7a086d2a8c484765a61a94d1369277eb/.eggs/Cython-3.0.10-py3.10-macosx-10.9-x86_64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for phydms
Failed to build phydms
ERROR: Could not build wheels for phydms, which is required to install pyproject.toml-based projects
```

I have Python 3.10.14 and am on Mac OS 14.4.1. Any ideas on if I can do anything?

**Comment by jbloom** [comment]
Gosh, I don't really know how to debug this type of installation problem. Does it help if you use the `pip install --use-pep517` recommended in the error message?

**Comment by kevinmyers** [comment]
That worked! Thanks!
