### ISSUE TITLE
Error when using Pip to install phydms

### ISSUE THREAD

**Issue by mokiine** [jbloomlab/phydms#47]
I'm using Python3.8 to install phydms directly by 'pip install phydms' when error occured:

> Collecting weblogo<3.6,>=3.4 (from phydms)
  Using cached weblogo-3.5.0.tar.gz (434 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "c:\users\36255\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\36255\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\36255\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\36255\AppData\Local\Temp\pip-build-env-5illi8zh\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\36255\AppData\Local\Temp\pip-build-env-5illi8zh\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\36255\AppData\Local\Temp\pip-build-env-5illi8zh\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\36255\AppData\Local\Temp\pip-build-env-5illi8zh\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "C:\Users\36255\AppData\Local\Temp\pip-install-u8tk6cca\weblogo_9bf4f501288e438ab3f1dc4258a84a15\weblogolib\__init__.py", line 102, in <module>
          from numpy import array, asarray, float64, ones, zeros, any, int32, all, shape
      ModuleNotFoundError: No module named 'numpy'

I've tried several numpy versions but none of them worked. Would you please provide some advise? Thanks!

**Comment by jbloom** [comment]
Ugghh, these installation issues are hard to troubleshoot. What platform are you using? I can get it working on Linux, but I haven't really tried on other platforms.

**Comment by mokiine** [comment]
I foun

**Comment by mokiine** [comment]
I tried to install it on Windows but failed, maybe the x86 platform is not supported? Anyway I've solved it on Ubuntu. 
Sorry for bothering you with my misunderstanding, and I really appreciate your enthusiasm :)
